version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fluxolog_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fluxolog
    ports:
      - "5435:5432" # O Windows vai usar a 5435 porque ja ta usando o anterior
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: